/**
 * Primitive palettes. Ten steps per hue; step 5 is the base used by default in
 * light mode, step 4 in dark mode (lighter, because it sits on a dark ground).
 *
 * The ramps are hand-tuned for even perceptual spacing rather than generated by
 * lightening/darkening one hex, which is what makes mid-steps look muddy.
 * Primitives are never referenced by components — semantic tokens map them to
 * roles, and that indirection is what makes retheming safe.
 */
export type PaletteScale = readonly [
  string, string, string, string, string,
  string, string, string, string, string,
];

export const palettes = {
  /** Cobalt with a faint violet undertone at the deep end — the brand hue. */
  brand: [
    '#f0f4ff', '#dde7ff', '#c0d1ff', '#97b3ff', '#6b90fb',
    '#4169ef', '#2f4fd0', '#263ea6', '#223582', '#1a2857',
  ],
  green: [
    '#ecfdf3', '#d1fadf', '#a6f4c5', '#6ce9a6', '#32d583',
    '#12b76a', '#039855', '#027a48', '#05603a', '#054f31',
  ],
  red: [
    '#fef3f2', '#fee4e2', '#fecdca', '#fda29b', '#f97066',
    '#f04438', '#d92d20', '#b42318', '#912018', '#7a271a',
  ],
  amber: [
    '#fffaeb', '#fef0c7', '#fedf89', '#fec84b', '#fdb022',
    '#f79009', '#dc6803', '#b54708', '#93370d', '#7a2e0e',
  ],
  /** Neutrals carry a slight cool bias so they sit with the brand hue. */
  gray: [
    '#f6f7f9', '#eceef2', '#dfe3e9', '#cbd1db', '#a4adbd',
    '#7b8598', '#5a6376', '#414958', '#2a303c', '#171b23',
  ],
} as const satisfies Record<string, PaletteScale>;

export type PaletteName = keyof typeof palettes;

/** Dark-mode surfaces are their own ramp: tinted charcoal, never pure black. */
export const darkSurfaces = {
  page: '#0d1015',
  container: '#14181f',
  elevated: '#1b202a',
  raised: '#222836',
} as const;

export const constants = {
  white: '#ffffff',
  black: '#000000',
  transparent: 'transparent',
} as const;
