/**
 * Compiles the TypeScript token source into a single stylesheet.
 *
 * Output contract (consumed by @i-design/core styles):
 *   :root                          -> light + default density
 *   [data-i-theme="dark"]          -> dark overrides (explicit opt-in)
 *   @media (prefers-color-scheme)  -> dark overrides when the app opted into "auto"
 *   [data-i-density="compact"|...] -> density overrides
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const dist = resolve(here, '../dist');
const { lightTokens, darkTokens, shapeTokens, densityTokens, toCssVarName, primitiveVars } =
  await import(resolve(dist, 'index.js'));

const block = (selector, tokens, indent = '') => {
  const body = Object.entries(tokens)
    .map(([k, v]) => `${indent}  ${toCssVarName(k)}: ${v};`)
    .join('\n');
  return `${indent}${selector} {\n${body}\n${indent}}`;
};

// Primitives are plain RGB triplets; semantic tokens reference them through
// rgba(), so the primitive block has to come first.
const primitives = Object.entries(primitiveVars())
  .map(([name, value]) => `  ${name}: ${value};`)
  .join('\n');

const parts = [
  '/* i-design tokens — generated by packages/tokens/scripts/build-css.mjs. Do not edit. */',
  `:root {\n${primitives}\n}`,
  block(':root', { ...shapeTokens, ...densityTokens.default, ...lightTokens }),
  block('[data-i-theme="dark"]', darkTokens),
  `@media (prefers-color-scheme: dark) {\n${block('[data-i-theme="auto"]', darkTokens, '  ')}\n}`,
  ...Object.entries(densityTokens).map(([name, tokens]) =>
    block(`[data-i-density="${name}"]`, tokens),
  ),
];

await mkdir(dist, { recursive: true });
await writeFile(resolve(dist, 'tokens.css'), parts.join('\n\n') + '\n', 'utf8');
console.log('[tokens] wrote dist/tokens.css');
